### PR TITLE
Fix exit scene behavior (when exit is anticipated)

### PR DESCRIPTION
**Pull request by Splines**
In this PR, we fix the following situations:
1. Start Scene somewhere. Then start scene at another line. Confirm `Kill it`. Before this change, this resulted in a new scene being created and after that being immediately destroyed. The Manim Shell was left in a weird state.
2. Preview a Manim Cell. While previewing issue "Start scene" somewhere else and confirm `Kill it`. Before this change, the progress notification would remain frozen in the last position indefinitely.
3. Preview a Manim Cell. While previewing, manually open a new terminal, start `manimgl` in there. The first session should automatically exit, while the second is booting up.

### Known limitations
- We currently don't detect when the user forces the shell to exit by other means, e.g. by clicking on the trash bin. This may result in indefinite progress bars when force-quitting the shell during previewing. This can be tackled in a future PR.

### CODE REVIEW

**Comment by bhoov** [comment]
image

It seems like I am now unable to start a terminal at all on my device. Could this be because I am running inside a `conda` environment where `manimgl` is installed?

**Comment by Splines** [comment]
Cold you check again if it's working now? And make sure to have a clean state, sometimes during extension development VSCode has some caching issues during reload, so start with a fresh new instance. (at least this was sometimes a problem for me)

> Could this be because I am running inside a `conda` environment where `manimgl` is installed?

No, I don't think this would be an issue. We are only erroring in case we are trying to spawn a new shell but receive an `TerminalShellExecutionEndEvent`. We're not even checking if there's anything special about the user's environment. We just want to see the manim welcome string and then the first `In [1]:` statement and then we know we have successfully started.

So, when you receive this error message, the terminal should also open up automatically. What does it show?
Does this problem only occur with this PR, not already with #45? So on `main`, it's working for you, just not here?

**Comment by VladimirFokow** [comment]
> image
> 
> It seems like I am now unable to start a terminal at all on my device. Could this be because I am running inside a `conda` environment where `manimgl` is installed?



This can happen if you e.g. place your cursor here:


```py

class SquareToCircle(Scene):
    def construct(self): <--- here, on the `construct` method
<--- here, on empty lines just before the line with `construct` method
<---
<---
        ## Set up
        circle = Circle()
        circle.set_fill(BLUE, opacity=0.5)
        circle.set_stroke(BLUE_E, width=4)
        square = Square()
        #
```

The fix is easy - we just need to add this logic to `startStopScene.ts`

I just overlooked this edge case the first time when I wrote it

**Comment by VladimirFokow** [comment]
@Splines , I just tried this branch - I have the error

**Comment by VladimirFokow** [comment]
@Splines , you wrote 3 points above.

I checked:

- works 👍
- I still get: "No active Manim session found to exit."
- auto-exits👍. But I still get: "No active Manim session found to exit."


Thoughts:

- I love (!) the integration right with the VSCode notifications!!

- question: do we need to kill old Manim window before starting a new one? 
  Can't we have multiple Manims running at the same time - just in multiple terminals?
  Do we need to auto-exit from the previous one if the user opens a new terminal and types `manimgl`? That doesn't sound permissive to the user..

**Comment by Splines** [comment]
Thanks for testing this out @VladimirFokow! As a few things have changed in the meantime, would you mind checking it out again? And if it doesn't work, could you attach respective log files, where each of them tries to do as minimal things as possible? (e.g. one for each scenario)

---

> why do we need to kill the old Manim window before starting a new one?
Can't we have multiple Manims running at the same time - just in multiple terminals?

In theory it'd be possible to spawn multiple Manim instances. But the situation I try to avoid is the following:
- User wants to preview some code, so Manim is started in a new terminal.
- User manually opens up another terminal and types in `manimgl`. This is fine and should already work: we detect the new terminal as "Manim host" when we see the `ManimGL` string in the Terminal (this exact capitalization), followed by the first IPython cell. So this new terminal will be used to preview cells. At this state it'd be perfectly fine to have multiple Manim sessions open.
- Now image we didn't kill the session that is still running in the first terminal. The user decides to quit the second terminal and switches over to the first one. They expect that "Preview Manim Cell" will use this terminal now, which is not the case. The problem is that Manim was already spawned in this terminal, but later we used the second terminal. So from the point of view of the code, we don't know that manim is still running in the first one. And we didn't retrieve the `ManimGL` string from that terminal a second time, so we don't know that this is a "Manim host". Therefore, clicking on "Preview Manim Cell" would again open a new Manim session and the user would be confused.

In theory, supporting the scenario would be possible. But that'd require even more state management, e.g. we'd have to track the terminals and multiple Manim executions across different terminals. I just didn't want to do that, which is why I settled with this limitation (which I don't think is a serious limitation: why would you want to have two Manim previews open at the same time anyways?)

**Comment by VladimirFokow** [comment]
currently this happens:

Log:
[Manim Notebook.log](https://github.com/user-attachments/files/17587621/Manim.Notebook.log)


https://github.com/user-attachments/assets/3300d0dd-fca6-4de4-bc12-09e954a0eb3b


```py
from manimlib import *


class MyScene(Scene):
    def construct(self):
        ## Test
        print('1')
```

**Comment by Splines** [comment]
@VladimirFokow Ready for another review ;)

**Comment by VladimirFokow** [comment]
1, 2 don't work.

Log: [Manim Notebook.log](https://github.com/user-attachments/files/17588504/Manim.Notebook.log)

**Comment by VladimirFokow** [comment]
I suspect this might have broken it:
https://github.com/bhoov/manim-notebook/pull/64

**Comment by Splines** [comment]
Just that we're at the same page: what does "before" in `It worked before.` refer to? Now with `main` merged back into this one, what is different compared to your first comment:

> works 👍
> progress notification disappears 👍, but I still get: "❌ No active Manim session found to exit."
> it auto-exits 👍, but I still get the same as above: "❌ No active Manim session found to exit."

Could you maybe attach some logs for the specific cases 1, 2 and 3?

**Comment by VladimirFokow** [comment]
## on commit 58f06caae32c9158bec1a2c14d501b9b7cf53e7a:

- 1 doesn't work:

[Manim Notebook.log](https://github.com/user-attachments/files/17589018/Manim.Notebook.log)


https://github.com/user-attachments/assets/43d8e942-a4a6-4ccb-85b2-e62df1e24624

**Comment by VladimirFokow** [comment]
Works on: 409c90643ca414ad1d1b2006b64d0d7b51cf1357


https://github.com/user-attachments/assets/35d90f53-a68f-49ba-b9f9-52a64136b281

**Comment by Splines** [comment]
Thank you for the reports! If in 58f06ca you place a logging statement right before the `return` here:

https://github.com/bhoov/manim-notebook/blob/58f06caae32c9158bec1a2c14d501b9b7cf53e7a/src/manimShell.ts#L334-L336

Will it show up for you in the log, even though you press `Kill it`?

**Comment by Splines** [comment]
Ok, so as I expected... And with 627ca8a, the log will show `❌ User selection undefined, but shouldn't be`?

**Comment by Splines** [comment]
Nevermind, found the error, will fix it

**Comment by Splines** [comment]
It should work now, right?

**Comment by VladimirFokow** [comment]
still doesn't..

**Comment by Splines** [comment]
ok, I can confirm, doesn't also work on my machine, will investigate

**Comment by Splines** [comment]
Ok, apparently I'm a bit unconcentrated 😅 Now it should work with 9879a7e

**Comment by VladimirFokow** [comment]
great, now 1 works again!

**Comment by VladimirFokow** [comment]
but the above mentioned errors in 2 and 3 still persist

**Comment by Splines** [comment]
Ok, at least 1 works now ;) Could you send me logs for 2 and 3 based on the current state, i.e. 9879a7e?

**Comment by VladimirFokow** [comment]
3

[Manim Notebook.log](https://github.com/user-attachments/files/17589811/Manim.Notebook.log)

https://github.com/user-attachments/assets/9f0e0cea-6eb7-4937-9a11-43d5055a581d

**Comment by Splines** [comment]
Ah ok, yeah the reason is that I send a keyboard interrupt to close the active running session (but stay in IPython), then send an `exit()` command to exit the scene. But of course that doesn't work on MacOS since already the keyboard interrupt closes everything.... So that's why we get the error since after closing (via `Ctrl+C`), it won't find an active shell to close 😅

Another idea might be to just force-kill the respective VSCode terminal. Then the behavior should be independent on Linux or MacOS.

**Comment by VladimirFokow** [comment]
I like killing the terminal because then the user won't have the dangling terminals after every restart

**Comment by Splines** [comment]
ok will implement this now

**Comment by VladimirFokow** [comment]
first interrupt, then force-kill?

**Comment by VladimirFokow** [comment]
because just force killing may cause some bad state?

**Comment by VladimirFokow** [comment]
If I force-kill the 1st manim terminal,

when starting the 2nd, I have this hanging:

Screenshot 2024-10-31 at 17 49 11

**Comment by Splines** [comment]
Yes, this is a known limitation from an earlier PR because we don't detect when terminals are manually disposed by the user. But it's not a problem programmatically since at the required step we know we now throw away the terminal, so we can just reset the state at that point.

**Comment by Splines** [comment]
In e10359e I fixed the `try-catch` error handling which I have done just outright wrong as I was used to how other languages handle the `catch` blocks. Here, instead we have to check for `isinstanceof`.

Now with 22663a7, I reworked the exit mechanism to force-quit.

**Comment by VladimirFokow** [comment]
ah. I think we can finally put this PR to rest 😅😅

**Comment by Splines** [comment]
One last problem I just discovered is that when previewing a long command, then using the command to quit the scene, the scene will continue to finish rendering and only then exits the ManimGL preview window. Will investigate.

**Comment by VladimirFokow** [comment]
> the scene will continue to finish rendering

Even if I manually delete the terminal, this still happens

**Review by VladimirFokow — APPROVED** [review]

**Comment by Splines** [comment]
What about now?

**Comment by VladimirFokow** [comment]
If I quit in the middle of long-running previewing, now:

 > /Users/vladimir/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown

**Comment by Splines** [comment]
> If I quit in the middle of long-running previewing, now:

But not by trashing the terminal manually. You use the Quit Scene command provided by us, right?

**Comment by Splines** [comment]
This is the behavior I get as of 293b93d

https://github.com/user-attachments/assets/3ac8e853-6b17-4fea-b520-5aeefbe24398

**Comment by Splines** [comment]
> /Users/vladimir/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown

How do you even see these error messages now that the terminal is disposed almost immediately (after sending keyboard interrupt and a small delay of 250ms)?

**Comment by VladimirFokow** [comment]
By trashing manually - it's awful

- even if I got that warning, I trashed the terminal, so the warning is also trashed
- the scene still continues to run
- the progress bar is stuck at the point when I trashed it

**Comment by VladimirFokow** [comment]
I would vote to revert the last commit & merge

**Comment by VladimirFokow** [comment]
please read this carefully:

https://github.com/bhoov/manim-notebook/pull/48#issuecomment-2450405618

**Comment by Splines** [comment]
> By trashing manually - it's awful

As I wrote earlier, this PR does not deal with the case where you trash the terminal manually. See the title of this PR: `when exit is anticipated`. This could something for a subsequent PR, but this one is not dealing with it. Only using the commands that we provide in the extension.

**Comment by VladimirFokow** [comment]
okay, good that we got this clear
(I thought you asked at some time and then deleted it)

**Comment by Splines** [comment]
> (I thought you asked at some time and then deleted it)

What is "it" in "deletet it"? Your conversation? Now, not at all, I've just marked one of the message as off-topic, that's all ;)

**Comment by VladimirFokow** [comment]
> How do you even see these error messages

- when I press Ctrl+C manually - I see it

- when I run the stop command - the terminal isn't deleted, so it's there in the terminal

**Comment by VladimirFokow** [comment]
hm.. now it's disposed.. let me check again

**Comment by Splines** [comment]
Sorry, but I'm not sure how the current behavior looks like at your end. You use `Quit preview` and the terminal still stays up running?

If the behavior is indeterministic for you, I think I know why and could fix that...

**Comment by Splines** [comment]
I just want to check one more thing, could you please send me the log for just , that'd be awesome.

- Start scene at any line. (But don't preview code)
- Then use `Quit preview`

**Comment by VladimirFokow** [comment]
My behavior on commit 293b93dd1df14c92fdde9835d99f60ab3c7e05ee:

- preview long-running scene
- in the middle: "Manim Notebook: Quit preview"
- the terminal is NOT disposed. In that terminal I see the warning

**Comment by Splines** [comment]
> I see that some resourced leaked:

The fact that you see this when you press `Ctrl+C` shows that this is a Manim-problem and not ours, I guess. And this shouldn't be a big problem, we're trashing the terminal afterwards anyways and Python itself will do some resource-cleanup as well. And even if something leaks... well, then it leaks and the next time you start VSCode this leakage is probably gone...

But where this is of course a problem is when this hinders us somehow from disposing the terminal altogether. Could you maybe record a video for me to better understand what is going on at your end?

**Comment by Splines** [comment]
But it should always be possible to just force-quit any task. I mean we're in a terminal so we can stop anything if we want to. When using `manimgl` via the command line I'm employing `Ctrl+C` all the time if I don't want to continue to watch my preview. That's why I'd like to be able to quit any preview via the extension as well. It's the user's power: of course you might risk some leakage when you quit mid-preview, but is that really an issue? This is just a leakage _warning_; yes: possibly a small leakage did occur. But it's probably also so small as to go unnoticed. In the end, the OS will free up resources anyways in much deeper layers...

**Comment by VladimirFokow** [comment]
## Log 1:

[Manim Notebook.log](https://github.com/user-attachments/files/17591408/Manim.Notebook.log)

https://github.com/user-attachments/assets/6935e115-d882-40d4-844c-af33dc836cef

**Comment by VladimirFokow** [comment]
## Log 2:

[Manim Notebook.log](https://github.com/user-attachments/files/17591454/Manim.Notebook.log)

(sorry, accidentally clicked twice, but it shouldn't matter)

https://github.com/user-attachments/assets/7afabfb5-8e3a-4a56-80ad-d1a669ceae31

**Comment by VladimirFokow** [comment]
> we even ask the user to confirm Kill it. It's their choice

ok

**Comment by Splines** [comment]
> Log 2:

Thank you very much! In the background there is a trace shown for `startStopScene`, is that relevant? Or was it from a previous session?

**Comment by Splines** [comment]
The issue was again how MacOS handles the keyboard interrupt. It will end the whole IPython session, which is why a `TerminalShellExecutionEndEvent` is triggered. This in turn calls `this.resetActiveShell()`  which sets `this.activeShell = null;`. Therefore, we didn't have the reference to the active shell anymore. On Linux, we still have this reference since a `TerminalShellExecutionEndEvent` is never triggered in this case due to `Ctrl+C` just exiting the command inside the IPython kernel, but not the whole IPython kernel itself. Therefore, I didn't encounter this problem.

Now to mitigate this, I temporarily store the last active shell before sending the keyboard interrupt. This way, when it comes to disposing the terminal, we still have a valid reference. See 9abc645

**Comment by Splines** [comment]
Just by the way, when you start the `Record Log File` command. You don't always have to select the log level. Just press `Esc`. If you've set it once to `Trace` it will stay in this setting for the next runs.

**Comment by VladimirFokow** [comment]
> Just by the way, when you start the `Record Log File` command. You don't always have to select the log level. Just press `Esc` once clicked on the command. If you've once set the log level to `Trace` it will stay in this setting for the next runs.

oh, thanks!
could you please add it to the readme as well?

**Comment by Splines** [comment]
Sorry I revoked my comment since it wasn't true. You can't just press `Esc`. While the default for the extension will stay the same (when not reloading the window, just using the command multiples times), you still have to select the extension in the dropdown, otherwise the global default will be considered (which is `Info`).

**Comment by VladimirFokow** [comment]
This fixed the issue: https://github.com/Manim-Notebook/manim-notebook/pull/48#issuecomment-2450533185

**Comment by VladimirFokow** [comment]
> Sorry I revoked my comment since it wasn't true. You can't just press `Esc`. While the default for the extension will stay the same (when not reloading the window, just using the command multiples times), you still have to select the extension in the dropdown, otherwise the global default will be considered (which is `Info`).

I think I just tested it, and got the opposite result..

Anyway, it's not important. We won't change the readme

**Comment by Splines** [comment]
Since you've already approved: just write a comment once you approve this PR ;)

**Comment by VladimirFokow** [comment]
can merge

**Comment by Splines** [comment]
Wohoo, nice that it works now for you as well 💫 Lesson learned, exiting is not as easy as expected ;) This would be a lot easier if there was a fix for https://github.com/3b1b/manim/discussions/2236

A future PR can now tackle the case where the user manually disposes a terminal. In this case, we want to detect this event and then reset the state accordingly.

**Comment by Splines** [comment]
And thanks a lot for your on-going manual testing support in this one @VladimirFokow ❤

**Comment by VladimirFokow** [comment]
I should have done all this myself,
I just didn't have the capacity to dive into the code yet

**Comment by Splines** [comment]
Don't worry there will be enough future issues waiting for you ;)

**Comment by VladimirFokow** [comment]
please no😅
Let's try writing code without any issues the 1st time)

**Comment by Splines** [comment]
> Let's try writing code without any issues the 1st time)

Haha, that's the goal, but rarely achievable in real life (I speak from experience, even with a nice testing harness, there will still be bugs). Otherwise it'd be too boring 😅

**Comment by Splines** [comment]
And just a little remark for the future @bhoov @VladimirFokow : you don't have to review code in PRs that are marked as draft 😇. Just to not waste any time since those PRs are usually a little bit of my playground until I finalize them. Beforehand, lots of things won't work even though the PR itself might look like all the features are implemented.

**Pull request merged**
