### PR TITLE
Redesign Manim cells (and make more prominent)

### PR DESCRIPTION
**Pull request by Splines**
When working with our extension, I sometimes had a hard time identifying where cells end and start. Therefore,
- increase focused cell border width
- increase starting cell comments weight (they are not printed in bold)
- go with some (admittedly bold) new color scheme I came up with

Here's what the new redesign looks like for different themes. Please check the following themes locally:
- dark & dark (high contrast)
- light & light (high contrast)

**Edit: The default color choice is now a blue-tone, not a red-tone anymore as shown in these images.**

New Manim Cell Look

The kind of blueish red-tone I've chosen sets us apart in the sea of different colors in the editor. But of course color choice is very subjective, that's why users can choose any color they want in their `workbench.colorCustomizations` section. The ids for the colors we contribute will we visible in the extension overview page when installing it as written [here](https://code.visualstudio.com/api/references/theme-color#extension-colors). E.g. try out (only in light themes):

```json
"workbench.colorCustomizations": {
    "manimNotebookColors.baseColor": "#005EC7",
    "manimNotebookColors.unfocused": "#B1D3FA"
}
```

### CODE REVIEW

**Comment by VladimirFokow** [comment]
- I would leave the previous blue as the default
- where is the setting to change the color? I couldn't find it in settings

**Comment by Splines** [comment]
> Can we have the color setting simply in the "Manim Notebook" settings?

Technically, I'm sure there's a way to do this. But then consider that the way I implemented it is the [default way proposed by VSCode](https://code.visualstudio.com/docs/getstarted/themes#_customize-a-color-theme) and theme plugin authors rely on it. Of course, we could make this option more prominent in some kind of docs.

**Comment by VladimirFokow** [comment]
I'm ok with `workbench.colorCustomizations` 👍

then we just add the instructions to the readme

**Comment by Splines** [comment]
> But I would leave the blue color by default (like the default was),

Yeah, I think you're right, maybe the red-ish colors are too much of a bold move as it is quite a dominant color. I've tried to settle for a more balanced blue-tone now, please try it out with different themes.

> Then we should add the instructions to the readme as well in this PR, right?

Yes, absolutely. I've added respective sections to the Readme to show users how to customize color choices. The red-tone I was originally using is now available via copy-paste from that Readme ;)

> Can we also add a checkbox (in the settings) for users who want to DISABLE these visual lines at the start & end of each cell?
(and any boldness / style as well)?

I've added two respective settings for this.

**Review by bhoov — APPROVED** [review]
Sorry for the hiatus. Thank you for changing the default color back to blue -- it is the "familiar" color for those coming from the jupyter extension. README update also looks good. I approve

**Comment by Splines** [comment]
> Sorry for the hiatus. 

No worries, thanks for the review! 🙏

**Pull request merged**
